### PR TITLE
Convert existing Solidity tests to JS and refactor existing JS tests (closes #29 and #21)

### LINKED ISSUE #29: Refactor the existing Javascript tests to use the layout suggested where the It-Should definitions are all at the top.
As per the title

### PR DESCRIPTION
**Pull request by AndyWatt83**
We discussed refactoring the tests to group together the it('should...') statements. Implemented on the TestCoinTossMock tests for a look.

### CODE REVIEW

**Comment by AndyWatt83** [comment]
Have a look over the latest changeset and see what you think. I'm a bit on the fence tbh.

**Comment by GarethOates** [comment]
You don’t like the description being at the top? I think it’s great. Nice and easy to see exactly how the contract should behave.

**Comment by AndyWatt83** [comment]
Yeah, it looks quite good. Somewhat hides the implementation, which I guess with tests is fine. If they pass, you don't really need to know how they are implemented.

**Comment by GarethOates** [comment]
Have converted the old solidity tests to javascript and completed the refactoring of the existing javascript tests to the format we agreed, with the "it should" at the top.

**Pull request merged**
